import { StyleSheet } from "react-native";
import responsive from "../../utils/responsive";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "white",
    paddingTop: responsive(40)
  },
  title: {
    fontSize: responsive(24, true),
    marginBottom: responsive(20),
  },
  linearGradient: {
    width: responsive(350),
    height: responsive(160),
    position: 'absolute',
    alignSelf: 'center',
    justifyContent:"center",
    borderRadius: responsive(20),
    paddingHorizontal: responsive(10),
  },
  innerView: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "95%",
    marginTop:responsive(20)
  },
  flatcontainer: { width: responsive(80), alignItems: 'center', marginRight: responsive(0) },
  flatImg: { width: responsive(50), height: responsive(50), borderRadius: responsive(25) },
  flatUserName: { fontSize: responsive(12, true), color: "white", textAlign: 'center', marginTop: responsive(5) },
  recentFlatContainer: { width: '100%', alignItems: 'center', flexDirection: "row", justifyContent: "space-between", marginBottom: responsive(15) },
  recentFlatContainerInner: { flexDirection: "row", alignItems: "center" },
  recentFlatImg: { width: responsive(18), height: responsive(18), tintColor: "white" },
  recentFlatTextContainer: { marginLeft: responsive(20) },
  recentFlatActivity: { fontSize: responsive(14, true), color: "white", marginTop: responsive(5), fontWeight: "bold" },
  recentFlatDate: { fontSize: responsive(10, true), color: "gray", marginTop: responsive(5), fontWeight: "bold" },
  recentFlatMoney: { fontSize: responsive(10, true), color: "gray", marginTop: responsive(5), fontWeight: "bold" },
  headerContainer: { paddingHorizontal: responsive(20), marginTop: responsive(20), justifyContent: "space-between", flexDirection: "row", alignItems: "center" },
  menuBtn: { width: responsive(30), height: responsive(30), backgroundColor: "lightgray", borderRadius: responsive(15), padding: responsive(5), justifyContent: "center", alignItems: "center" },
  menuImg: { width: '80%', height: "80%" },
  headerTextContainer: { width: responsive(120), height: responsive(40), backgroundColor: "black", borderRadius: responsive(20), padding: responsive(8), flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  headerTextInnerContainer: { backgroundColor: "white", height: "100%", width: '70%', borderRadius: responsive(20), alignItems: "center", flexDirection: "row", padding: responsive(5) },
  headerView: { width: responsive(18), marginRight: responsive(5), height: responsive(18), borderWidth: 2, borderColor: "black", alignItems: "center", borderRadius: responsive(10), justifyContent: "center" },
  dollarText: { color: "black", fontSize: responsive(10, true), fontWeight: "bold" },
  balanceText: { color: "black", fontSize: responsive(10, true), fontWeight: "bold" },
  swapView: { width: responsive(18), height: responsive(18) },
  swapImg: { width: '100%', height: "100%", tintColor: "white" },
  notificationView: { width: responsive(30), height: responsive(30), backgroundColor: "lightgray", borderRadius: responsive(15), padding: responsive(5), justifyContent: "center", alignItems: "center" },
  notificationIcon: { width: '80%', height: "80%" },
  amountContainer: { paddingHorizontal: responsive(20), marginTop: responsive(20), flexDirection: "row", alignItems: "center", justifyContent: 'space-between' },
  balanceAmountText: { color: "gray", fontSize: responsive(14, true) },
  balanceAmount: { color: "black", fontSize: responsive(30, true), fontWeight: "bold" },
  plusContainer: { width: responsive(30), height: responsive(30), borderRadius: responsive(15), borderStyle: "dashed", borderWidth: 1, justifyContent: "center", alignItems: "center" },
  plusImg: { width: '60%', height: "60%" },
  bottomContainar: { marginTop: responsive(20) },
  detailContainer: { marginTop: responsive(50), backgroundColor: "black", height: '100%', borderTopLeftRadius: responsive(30), borderTopRightRadius: responsive(30) },
  innerButtonContainer: { width: "100%", paddingHorizontal: responsive(20), marginTop: responsive(120), flexDirection: "row" },
  monetButton: { width: "50%", height: responsive(50), flexDirection: "row", alignItems: "center", justifyContent: "center", backgroundColor: "#fbc63b", borderRadius: responsive(25) },
  connectionImg: { width: '10%', height: "30%", tintColor: "black" },
  transferText: { fontSize: responsive(14, true), fontWeight: "bold", marginLeft: responsive(5) },
  requestBtn: { width: "50%", height: responsive(50), flexDirection: "row", alignItems: "center", justifyContent: "center", backgroundColor: "#171717", borderRadius: responsive(25) },
  requestImg: { width: '10%', height: "32%", tintColor: "white" },
  requestText: { fontSize: responsive(14, true), fontWeight: "bold", marginLeft: responsive(5), color: "white" },
  dataContainer: { width: "100%", paddingHorizontal: responsive(20), marginTop: responsive(30) },
  dataInnerContainer: { flexDirection: "row", justifyContent: "space-between" },
  quickText: { fontSize: responsive(14, true), fontWeight: "bold", marginLeft: responsive(5), color: "white" },
  seeAllText: { fontSize: responsive(10, true), fontWeight: "bold", marginLeft: responsive(5), color: "#fbc63b" },
  flatContainer: { width: "100%", marginTop: responsive(15) },
  activityContainer: { width: "100%", paddingHorizontal: responsive(20), marginTop: responsive(30) },
  innerBtnView: { flexDirection: "row", justifyContent: "space-between" },
  recentText: { fontSize: responsive(14, true), fontWeight: "bold", marginLeft: responsive(5), color: "white" },
  seeAll: { fontSize: responsive(10, true), fontWeight: "bold", marginLeft: responsive(5), color: "#fbc63b" },
  activityFlatContainer: { width: "100%", marginTop: responsive(15) },
  cardNumberText: { color: "black", fontSize: responsive(18, true), fontWeight: "bold" },
  ringsView: { flexDirection: "row", width:responsive(50) },
  filledRing: { width: responsive(25), height: responsive(25), backgroundColor: "black", borderRadius: responsive(12.5) },
  emptyRing: { width: responsive(25), height: responsive(25), borderRadius: responsive(12.5), borderWidth: 5, position: "absolute", left: responsive(18) },
  linerTextContainer: { marginTop: "auto", flexDirection: "row", justifyContent: "space-between", marginBottom:responsive(10), width:"95%"},
  holderName: { color: "black", fontSize: responsive(10, true) },
  name: { color: "black", fontSize: responsive(16, true), fontWeight: "bold" },
  expiryDate: { color: "black", fontSize: responsive(10, true) },
  date: { color: "black", fontSize: responsive(16, true) }
});

export default styles